# Generated by Django 4.2.1 on 2023-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('sun', 'sunny'), ('cloud', 'cloudy'), ('wind', 'windy'), ('Sun', 'sunny'), ('storm', 'stormy')], max_length=5)),
            ],
        ),
    ]
